### ISSUE TITLE
Multiple events tracking at single point

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#105]
Hello,

We are trying to track multiple events from a single point in code - say on a button click. We tried to track 3 events, but only one of them was successful. Could you please let us know how to track simultaneous multiple events.

**Comment by uerceg** [comment]
Hi @samirpramanik 

Can you please try to perform this event tracking attempt with SDK set to sandbox and log level set to verbose, pick up the logs from this run and send them over?

Cheers

**Comment by samirpramanik** [comment]
Hi, please find the logs attached.
[adjust_simultaneous_fail.txt](https://github.com/adjust/cordova_sdk/files/4585103/adjust_simultaneous_fail.txt)

**Comment by uerceg** [comment]
Hi @samirpramanik 

I am noticing this in your logs: `Event tracked '<event_id>'`.

Seems like you are using wrong event token to track events because `<event_id>` is not valid event token. Did you hard code that string when creating event object? You event token should be six character string token taken from the dashboard.

**Comment by samirpramanik** [comment]
I just replaced my actual event token with event_id just to post in this public forum. The event id is fine. Actually, when we invoke single event it works fine, but when we try to track multiple events from a single point, only one event is getting tracked. I believe it is overwriting other events processes. Is there any way to make this work?

**Comment by uerceg** [comment]
Hi @samirpramanik 

Sorry for delay in reply. Can you please set log level in code to verbose and then send us all logs over for this test scenario? In here I see only up to debug (`D/Adjust`) log level and I need verbose level as well. You can set that by calling this on your config object:

```js
adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);
```

**Comment by ugi** [comment]
Hi @samirpramanik 

Any update in here?

**Comment by uerceg** [comment]
Feel free to comment/reopen in case you still have issues with this. Cheers.
