### ISSUE TITLE
Event not getting tracked

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#106]
Hello,

I am constantly getting the following error when i am trying to track an event :
05-10 16:49:58.955: E/chromium(5595): [ERROR:aw_browser_terminator.cc(125)] Renderer process (5641) crash detected (code -1).
05-10 16:50:08.267: E/chromium(5595): [ERROR:aw_browser_terminator.cc(125)] Renderer process (5714) crash detected (code -1).

**Comment by uerceg** [comment]
Hi @samirpramanik 

Is there any chance to get full verbose logs when you're trying to track event in your app in sandbox mode?

**Comment by samirpramanik** [comment]
We are able to track the event now.

**Comment by uerceg** [comment]
HI @samirpramanik 

Great news! Thanks for the update. If it's not a secret, can you maybe share with us what the issue was, just for the future reference?

Cheers
