### ISSUE TITLE
Can we read install referrer value

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#111]
Hello,

Hope you are doing good! We are aware that Adjust sdk already implements install referrer and we can see the value in sandbox debug logs. Now, we have a requirement to use the value of referrer in our application. So, is there any way to read the referrer value from the cordova sdk in android and ios? Please let us know the approach.

**Comment by uerceg** [comment]
Hi @samirpramanik 

At this moment, no. We did not add any getter method in our API which would give you this value back. We do how ever have in plan to add this method in our next major SDK update which should arrive by end of the year. Until then, I guess you should try to read this value either on your own or with usage of some of the existing plugin. Haven't tried [this](https://github.com/byorty/cordova-install-referrer-api) one, but seems like it should be able to provide you information you need.

Cheers
