### ISSUE TITLE
No adjust id for Huawei app without GMS

### ISSUE THREAD

**Issue by tehmaestro** [adjust/cordova_sdk#113]
Hi, I'm using this plugin successfully in a regular Play Store app.
But when calling `Adjust.getAdid` on a Huawei AppGallery only device, I get a null result.
Also, the log sais, `Adjust not initialized correctly`.

Are there any additional steps for this to work with a Huawei device that doesn't have GMS?
Thanks.

**Comment by ugi** [comment]
Hi @tehmaestro 

`adid` is Adjust identifier for given device. It's a parameter which SDK gets from the backend upon first initialisation and successful tracking of install session. If that happened on the device, then our SDK will be able to provide you with non null value when you invoke `getAdid` getter. However, seems to me that in your case SDK didn't manage to speak with our backend, thus the null value returned.

Can you set up SDK to run in sandbox mode + turn log level to verbose and then send over the log of your app run where you're trying to test this (also would be good to uninstall app from test device prior to this test)? Feel free to omit any sensitive data from the logs.

Cheers

**Comment by tehmaestro** [comment]
Hi, I did a stupid mistake, sorry, everything works. Note to others: if you create a dedicated Huawei AppGallery app, you'll have to add the `.huawei` suffix to your package name .. well, make sure you don't apply any package name based filters for initializing adjust, or not .. which was what I was doing.

**Comment by ugi** [comment]
Glad it worked and thanks for the follow up. Good luck.
