### ISSUE TITLE
Update iOS SDK to version 4.23.0 

### ISSUE THREAD

**Issue by Luro91** [adjust/cordova_sdk#115]
Please update the iOS SDK to version 4.23.0, which is needed for iOS 14 support.
https://github.com/adjust/ios_sdk/releases/tag/v4.23.0

**Comment by ugi** [comment]
Hey @Luro91 

We have just released Cordova SDK [v4.23.0](https://github.com/adjust/cordova_sdk/releases/tag/v4.23.0).

Cheers!
