### ISSUE TITLE
requestTrackingAuthorizationWithCompletionHandler is still not accessible from Cordova plugin

### ISSUE THREAD

**Issue by learner2020-lab** [adjust/cordova_sdk#118]
Installed adjust plugin as below:
ionic cordova plugin add com.adjust.sdk
npm install @ionic-native/adjust

Could see 5.28.0 package and requestTrackingAuthorizationWithCompletionHandler is not found in node.ts and unable to invoke too.
Please let me know correct steps to add version with app-tracking changes as Cordova plugin to verify in iOS 14 beta.

Thanks!

**Comment by ugi** [comment]
Hi @learner2020-lab 

Sorry for delay and yes, we're trying to get latest API definition pushed to ionic-native repo. Will update once live.

**Comment by uerceg** [comment]
This should actually be live nowadays. In case you have any questions about this, feel free to comment/reopen. Cheers!
