### ISSUE TITLE
NullPointerException when calling getAttribution while the server communication is not completed

### ISSUE THREAD

**Issue by tehmaestro** [adjust/cordova_sdk#120]
Hi, I get this error:
```
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.adjust.sdk.AdjustAttribution.trackerToken' on a null object reference
        at com.adjust.sdk.AdjustCordovaUtils.getAttributionMap(AdjustCordovaUtils.java:147)
        at com.adjust.sdk.AdjustCordova.execute(AdjustCordova.java:81)
```
when calling getAttribution early after the app was installed. I understand that the method should not work, because the Adjust backend has not responded to the client app yet (adid is probably null still), but because of the error, the callback never gets executed back in JS.

I would propose that `attribution` object is checked for null value, in `AdjustCordova:81`.

**Comment by uerceg** [comment]
Hi @tehmaestro 

Thanks for reporting this and for the suggestion. Is this reproducible every single time for you when you call the getter prior to SDK obtaining attribution value?

**Comment by tehmaestro** [comment]
It is, yes.

**Comment by uerceg** [comment]
Thanks for the prompt answer. Fix for this will be added to next release. Will keep you posted on progress.

**Comment by tehmaestro** [comment]
For everyone that has this issue, what I did to fix the problem from the JS side is this.
I call `window.Adjust.getAdid` every 500 ms. As soon as an adjust id is available, not null, it is safe to call `getAttribution` without its callback not responding back.

**Comment by uerceg** [comment]
Thanks for the tip. Just for the record: We are aware that synchronous getter turned out not to be the best way to go, but within same major version (4.x.x) we're not gonna change behaviour, but next-year-to-come 5.x.x will have this API to be asynchronous and to remove the need for such workarounds as you mentioned above.

**Comment by uerceg** [comment]
Closing this one, but like mentioned, next major SDK release will address this. Cheers.

**Comment by thanhnb2** [comment]
I'm using version 4.28 and am having the above problem. Has the latest version fixed this problem? It's good that you can see this question.
