### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'

### ISSUE THREAD

**Issue by saviour2008** [adjust/cordova_sdk#123]
cordova android: 8.0.0
adjust_version: 5.29.0

I have installed @ionic-native/adjust and com.adjust.sdk through ionic cordova.

The installed status was successful.

It's throw error in terminal when build android
`D8: Program type already present: android.support.v4.os.ResultReceiver$1`
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.  
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
  Program type already present: android.support.v4.os.ResultReceiver$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.`

I research the error reason, There are duplicate_classes in some direct dependency on Library about this issue.

so could team member tell me how to resolve this issue?

**Comment by uerceg** [comment]
Hi @saviour2008 

Sorry for delayed response. Did you manage to solve this issue? Are duplicated classes from Adjust SDK? Did you manage to identify which other plugin was having classes added next to our plugin?

**Comment by ASynMed** [comment]
Hi,

We are facing the exact same issue:

cordova android: 8.0.0
com.adjust.sdk@4.26.0

> * What went wrong:
>    Execution failed for task
>    ':app:transformDexArchiveWithExternalLibsDexMergerForRelease'.
>    com.android.builder.dexing.DexArchiveMergerException: Error while merging
>    dex archives:
>    Learn how to resolve the issue at
>    https://developer.android.com/studio/build/dependencies#duplicate_classes.
>    Program type already present:
>    android.support.v4.os.ResultReceiver$MyResultReceiver

We use these other cordova plugins:

cordova-android-support-gradle-release
cordova-plugin-actionsheet
cordova-plugin-audioinput
cordova-plugin-badge
cordova-plugin-camera
cordova-plugin-camera-preview
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-file
cordova-plugin-inappbrowser
cordova-plugin-intercom
cordova-plugin-keyboard
cordova-plugin-meteor-webapp
cordova-plugin-network-information
cordova-plugin-printer
cordova-plugin-safariviewcontroller
cordova-plugin-splashscreen
cordova-plugin-statusbar
phonegap-plugin-barcodescanner

Are there any updates on this problem by any chance? Did you manage to identify the duplicate classes?

Thank you

**Comment by uerceg** [comment]
Does maybe suggested solution from [here](https://stackoverflow.com/questions/50676100/program-type-already-present-android-support-v4-os-resultreceivermyresultrecei) fix your issue?

**Comment by ASynMed** [comment]
Thank you @uerceg for the quick answer!

This gives us some clues to investigate but we can not directly apply the fix suggested by this post as we use the cordova framework.

**Comment by uerceg** [comment]
@ASynMed 

Sorry for delay in reply. Did you manage to solve the issue in the meantime? What prevents you from performing some of the suggested fixes from the StackOverflow posts? You should still be able to alter native projects even though you're building your app with Cordova.

Cheers

**Comment by uerceg** [comment]
If you're still facing this issue and in case you have any question(s) about it, feel free to comment/reopen.
