### ISSUE TITLE
Uncaught ReferenceError: AdjustConfig is not defined

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#125]
Hello,

I have upgraded to 4.23.0 from 4.14.0. Now, I am facing an issue when i am trying to create an instance of **AdjustConfig**.
Please find my implementation below which was working earlier in 4.14.0 :
`var adjustConfig = new AdjustConfig("abcdefg12345", AdjustConfig.EnvironmentSandbox);
adjustConfig.setLogLevel(AdjustConfig.LogLevelVerbose);   // enable all logging
adjustConfig.setLogLevel(AdjustConfig.LogLevelDebug);`

And the logs from console as below :
12-20 16:11:07.394: I/chromium(28233): [INFO:CONSOLE(57)] "Received Event: deviceready", source: file:///android_asset/www/js/index.js (57)
12-20 16:11:07.394: I/chromium(28233): [INFO:CONSOLE(60)] "Uncaught ReferenceError: AdjustConfig is not defined", source: file:///android_asset/www/js/index.js (60)

Please help with this as the same implementation was working fine with 4.14.0, there is no code change from my end, just the upgrade.

**Comment by samirpramanik** [comment]
Hello,

Any update?

**Comment by uerceg** [comment]
Hi @samirpramanik,

Sorry for a bit delay in responding (🎄). Did you manage to solve the issue or are you still facing it? Can you share a bit more information on your Cordova environment setup?

Cheers

**Comment by samirpramanik** [comment]
I understand that holidays are on.
Actually I was adding the latest adjust plugin using a third party tool for integration, which apparently missed certain plugin entries in the plugins folder and cordova_plugins.js. So, I installed the plugin via npm and added platform in the same way.

**Comment by uerceg** [comment]
Interesting, thanks for sharing. Does it work for you now when you added out plugin manually? And also for future reference, can you tell us which plugin was trying to add ours and caused this error?

**Comment by samirpramanik** [comment]
Yes it works fine now. Was trying to add adjust sdk 4.23.0.
