### ISSUE TITLE
ionic 5 - crashing on IOS 12, 13

### ISSUE THREAD

**Issue by azizcreativitykw** [adjust/cordova_sdk#131]
`Ionic:

   Ionic CLI                     : 6.12.2 (/Users/macbookpro/.nvm/versions/node/v10.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.4
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, ios 5.1.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)

Utility:

   cordova-res (update available: 0.15.3) : 0.15.2
   native-run                             : 1.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/macbookpro/Library/Android/sdk)
   ios-deploy        : 1.11.3
   ios-sim           : 8.0.2
   NodeJS            : v10.16.3 (/Users/macbookpro/.nvm/versions/node/v10.16.3/bin/node)
   npm               : 6.9.0
   OS                : macOS Big Sur
   Xcode             : Xcode 12.4 Build version 12D4e`

**Comment by uerceg** [comment]
Hi @azizcreativitykw 

Can you describe a bit more the crash itself? When does it happen? When you start the SDK, do something else with it? Can we get the crash stack trace?

**Comment by azizcreativitykw** [comment]
hi @uerceg 
 
thanks for the quick response
we don't have a device with ios 12
our client reported this issue, as soon they install the app on ios 12
the app gets crashed when they try to open
plz check the attached video

https://user-images.githubusercontent.com/66363246/110432460-35d28f80-80c0-11eb-8db3-802ec5fb753f.MP4

**Comment by azizcreativitykw** [comment]
@uerceg 

I have linked all the required framework in the app still it is crashing every time

[https://github.com/adjust/cordova_sdk#ios-frameworks](https://github.com/adjust/cordova_sdk#ios-frameworks)

<img width="1009" alt="Screen Shot 2021-03-10 at 12 38 18 PM" src="https://user-images.githubusercontent.com/66363246/110608655-7fdd7300-819d-11eb-93bf-c1114c930576.png">

**Comment by uerceg** [comment]
Hi @azizcreativitykw 

Thanks for this info and how about frameworks' linking status from this part?

<img width="1253" alt="Screenshot 2021-03-10 at 10 47 36" src="https://user-images.githubusercontent.com/1741635/110609931-0a1ddb00-818e-11eb-8a21-a8b8540d67ac.png">

**Comment by azizcreativitykw** [comment]
yes here also all frameworks are linked

<img width="1109" alt="Screen Shot 2021-03-10 at 12 57 59 PM" src="https://user-images.githubusercontent.com/66363246/110611418-3fcbbf80-81a0-11eb-8d1e-8f5e14aa99ee.png">

**Comment by azizcreativitykw** [comment]
@uerceg 

the issue is resolved now, thanks for your help

**Comment by uerceg** [comment]
No problemo, thanks for the update. In case you have any other questions on this topic, feel free to comment / reopen. Cheers.
