### ISSUE TITLE
Update the iOS SDK to 4.28.0 ASAP

### ISSUE THREAD

**Issue by jamesyoon11** [adjust/cordova_sdk#134]
Hi,

Our app got rejected by 

```
Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing

We found in our review that your app collects user and device information to create a unique identifier for the user's device. Apps that fingerprint the user's device in this way are in violation of the Apple Developer Program License Agreement and are not appropriate for the App Store.

Specifically, your app uses algorithmically converted device and usage data to create a unique identifier in order to track the user. The device information collected by your app may include some of the following: UIDevice, CTTelephonyNetworkInfo, getifaddrs, NSProcessInfo, and NSHomeDirectory.

Per section 3.3.9 of the Apple Developer Program License Agreement, neither you nor your app can use any permanent, device-based identifier, or any data derived therefrom, for purposes of uniquely identifying a device.
```

We believe this is caused by Adjust SDK and I see you guys already has address the issue.

https://github.com/adjust/ios_sdk/pull/526

So, can you please update the cordova plugins to use the iOS SDK 4.28.0 ASAP?

Best,

**Comment by uerceg** [comment]
Hi @jamesyoon11 

Absolutely. You can expect Cordova SDK v4.28.0 update today which will include native iOS SDK v4.28.0. Will keep you posted.

**Comment by uerceg** [comment]
Hey guys,

We have just released Cordova SDK v4.28.0. Feel free to give it a shot and in case you have further questions, feel free to comment/reopen.

Cheers!

**Comment by Himanshu-Mishr** [comment]
@uerceg Upon pulling new version, I am getting below error. 
```
```

**Comment by uerceg** [comment]
Hi @Himanshu-Mishr 

In case you want to use AdServices.framework, update your Xcode version to latest one or in case you don't need AdServices framework, feel free to remove it from your app.

**Comment by Himanshu-Mishr** [comment]
@uerceg Thanks for quick reply. Got clue from here https://github.com/adjust/unity_sdk/issues/214
