### ISSUE TITLE
iOS crashing on launch with: "-[UIDevice adjTrackingEnabled]: unrecognized selector sent to instance 0x600000e8d480"

### ISSUE THREAD

**Issue by ribalnasr** [adjust/cordova_sdk#136]
hello,

am using Ionic, with capacitor.
calling Adjust.create(config) after device is ready, is build ok with "ionic cap build --prod ios" but when the app is open in the simulator of on the device, its crashing and xcode is switching to the debug navigator and highlighting the following error:

Thread 2: "-[UIDevice adjTrackingEnabled]: unrecognized selector sent to instance 0x600000e8d480"

**Comment by ribalnasr** [comment]
Perfect!

**Comment by uerceg** [comment]
Hi @ribalnasr

Hm, weird. Which environment are you setting when running these tests? If sandbox, are you checking sandbox traffic in dashboard? If yes, can you run test install and maybe event tracking during that run with SDK set to sandbox and log level set to verbose and send the logs over? Feel free to omit any sensitive data from there if any.

**Comment by ribalnasr** [comment]
Hi @uerceg, sorry for wasting your time... after investigating this with the client's media company (the one that created the Adjust account), we found out that the issue was that they have given us the Android app token for the iOS too! I'm now updating the app with the correct token and hopefully everything will work out perfectly, otherwise I'll be back here... until then thank you for your time. :)

**Comment by uerceg** [comment]
No worries at all, glad you figured it out at the end. Cheers!
