### ISSUE TITLE
Ad transparancy popup background is coming as black instead of app screen in ionic Cordova based application

### ISSUE THREAD

**Issue by mpchaithra** [adjust/cordova_sdk#139]
We are able to get the ad transparancy popup after calling requestTrackingAuthorizationWithCompletionHandler() function and able to get the status also based on user input. But When the popup is displayed background is black and we are not able to see the application screen in the background.

We are using Ionic 5 in our app with Cordova and angular 11. 

Please make the necessary changes to get the transparent background when the popup is displayed.

**Comment by uerceg** [comment]
Hi @mpchaithra 

Sorry for a bit of delay in replying. Adjust SDK is not responsible for any UI moments in dialog which is being displayed. Only thing which Adjust SDK method you mentioned does is that it forwards the call to corresponding [native method](https://developer.apple.com/documentation/apptrackingtransparency/attrackingmanager/3547037-requesttrackingauthorizationwith?language=objc) and that's pretty much it. How dialog looks like is fully in power of iOS and not our SDK.

Cheers
