### ISSUE TITLE
CordovaError: Failed to fetch plugin https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git

### ISSUE THREAD

**Issue by anaiah** [adjust/cordova_sdk#140]
hi,

i'm having these err msgs when adding the plugin to my cordova project..

cordova plugin add https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git
Failed to fetch plugin https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 1 Error output:
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Roaming\npm-cache\_logs\2021-06-10T04_03_49_110Z-debug.log

pls help :(

**Comment by uerceg** [comment]
Hi @anaiah 

Seems like the plugin you're trying to add is not Adjust Cordova plugin, so not really sure if we can offer any meaningful assistance with the error you're facing with.

Cheers
