### ISSUE TITLE
Cordova Sdk integration - adjust

### ISSUE THREAD

**Issue by rogermaher1** [adjust/cordova_sdk#145]
![image](https://user-images.githubusercontent.com/89277563/130289780-1aca3a79-e985-4011-9529-ac7da1bf9bb9.png)
This is my project structure exported from Construct 3 as cordova project, Where should I put the integration code line ?
var adjustConfig = new AdjustConfig("{YourAppToken}", AdjustConfig.EnvironmentSandbox);
Adjust.create(adjustConfig);

**Comment by uerceg** [comment]
Hi @rogermaher1

To be honest, we never had an experience with what you did with your project (exporting Construct 3 into Cordova) so not really sure how things look like in there.

But when it comes to SDK initialization, universal rule applies to every platform we support: Do it as soon as possible, preferably right upon app launch.

In case you have any other questions on this topic, feel free to ping.

Cheers

**Comment by uerceg** [comment]
If you still need help with this one, feel free to comment / reopen. Cheers.
