### ISSUE TITLE
Add plugin to cordova/phonegap registry

### ISSUE THREAD

**Issue by krystalcode** [adjust/cordova_sdk#15]
Any view on adding the plugin to the cordova and phonegap build registries? That would ease automated build process a lot.

**Comment by sandstrom** [comment]
Any updates on this? :smile:

**Comment by wellle** [comment]
Not yet.

**Comment by zckrs** [comment]
Not yet publishing ?  http://plugins.cordova.io/#/search?search=adjust
:-(

**Comment by zckrs** [comment]
Done.

`cordova plugin add cordova-plugin-adjust` with cordova-cli v5.0.0

30min to fix a issue present since 28 Nov 2014 ... :see_no_evil:

**Comment by wellle** [comment]
Doesn't show up for me: http://plugins.cordova.io/#/search?search=adjust

**Comment by zckrs** [comment]
https://www.npmjs.com/package/cordova-plugin-adjust @wellle

**Comment by wellle** [comment]
Cool, thank you :+1:

**Comment by zwacky** [comment]
trying to get v4.0.0 and fails. am i doing something wrong?

`cordova plugin add cordova-plugin-adjust@4.0.0`

-> *Fetching from npm failed: version not found: 4.0.0*

**Comment by uerceg** [comment]
@zwacky Try with:

```cordova plugin add com.adjust.sdk@4.0.0```

and if you please let me know if it works.

Thanks in advance.

**Comment by zwacky** [comment]
thanks @uerceg, works perfectly
