### ISSUE TITLE
Enabling iOS frameworks

### ISSUE THREAD

**Issue by EOussama** [adjust/cordova_sdk#157]
How do we get to enable iOS frameworks as stated here?
https://github.com/adjust/ios_sdk#add-ios-frameworks

**Comment by uerceg** [comment]
Hi @EOussama,

As stated in [Cordova SDK README](https://github.com/adjust/cordova_sdk#ios-frameworks), Cordova SDK is already [adding these frameworks automatically](https://github.com/adjust/cordova_sdk/blob/master/plugin.xml#L89-L94), so you don't really need to take any additional actions to have them (weakly) linked.

In case you have any further questions, feel free to comment / reopen. Cheers.
