### ISSUE TITLE
Improve installation

### ISSUE THREAD

**Issue by sandstrom** [adjust/cordova_sdk#16]
It's awesome that you have a Cordova plugin, we choose you over a few of your competitors for that reason alone. Some thoughts on improvement though.

*Installation improvements*
- Keeping the `adjust.json` config file inside the plugin dir isn't that good, because that folder is a build artifact and not checked into version control. Either you should keep those values in the config.xml file, or in a file in the root cordova directory.
- Ideally a single-line install, via the cordova registry should be used. As a second option, being able to install from your git-repo would be nice. You could use a secondary repo for releases only, if you'd like to build output out of the repo (generally a good idea). Others do this[1]. More on plugin installs and how you could handle a 'deep' directory under *Advanced Plugin Options*[2].

*Configuration improvements*
- It seems like adjust must use one app per store, i.e. one for Android and one for iOS. Cordova built apps are typically deployed to both. Currently, your config has no method to facilitate this, one needs to hack the hook code to insert different `appToken` values depending on the platform.
- I think you can handle hooks without requiring people to copy files around, i.e. from within your plugin.

*Documentation improvements*
- It would be neat to know if with `enableEventBuffering` enabled, will it still 'flush' upon exit? Or are some events (e.g. open/install always sent immediately, despite it being enabled).

[1] https://github.com/components/ember-data
[2] http://cordova.apache.org/docs/en/4.0.0/guide_cli_index.md.html#The%20Command-Line%20Interface

**Comment by sandstrom** [comment]
Hey @wellle, just writing to see if there are any updates on this?

**Comment by wellle** [comment]
Nope, not yet.

**Comment by sandstrom** [comment]
Hi @wellle, any updates here? [friendly poke] :smile:

**Comment by nonelse** [comment]
hi @sandstrom, sorry for the delay. We're releasing the unity update now and checking what is the next one.
I'll update here when there is more info!

**Comment by sandstrom** [comment]
@nonelse Sounds good, thanks for keeping me in the loop!

**Comment by uerceg** [comment]
@sandstrom We have released `Cordova SDK 4.0.0` recently. If you would like, you can test the SDK and let us know in here if you would like us to add some new feature regarding this issue.

**Comment by sandstrom** [comment]
@uerceg Thanks, I will check it out and update here as soon as I have time.

**Comment by uerceg** [comment]
@sandstrom Any progress with this issue?

**Comment by sandstrom** [comment]
@uerceg not really, sorry! We have been busy with other things and haven't updated the client since July 24. This issue is noted and I will check as soon as I get around to another client update.

If you'd like to keep the open issues list clean, feel free to close this for now. We can re-open the issue (if needed) after I've checked it out.

**Comment by uerceg** [comment]
@sandstrom Thanks for the update on this one. If it's like that, I'll close it for now and if you face any issues regarding this topic later, feel free to reopen it. :+1:
