### ISSUE TITLE
Play Referrer installs - attribution problem

### ISSUE THREAD

**Issue by szepag** [adjust/cordova_sdk#165]
Hi,
We've noticed that vast majority of installs of our app do not follow with correct user attribution (mainly fb users).
Is it possible that it may be caused by not immediate initialisation of the Adjust plugin?
After the app starts there are some async tasks to be done before the AdjustConfig and Adjust.create are called.

**Comment by uerceg** [comment]
Hi @szepag,

In theory, that should not cause any issues (the way how your app starts and place where you are initializing Adjust SDK). Install referrer should have validity (value can be accessed) for 90 days after app has been installed, so our SDK will be able to pick up that information when you initialize it. You can also double check this when you launch the SDK in your app (if you set environment to sandbox + log level to verbose) - whenever the SDK is initialized after you installed your app, it will read install referrer content and send it to our backend via package called `sdk_click` where you will see `referrer` parameter carrying install referrer value and also inside of that package you should see parameter `source=install_referrer`. If that's happening, then everything is properly set for our SDK to read contents of Google Play install referrer.

**Comment by szepag** [comment]
@uerceg thank you for the reply, I've checked the logs and looks like there are install referrer data present.
However, as it stays in docs (https://developers.facebook.com/docs/app-ads/install-referrer/) the referrer data is encrypted in the `utm_content.source` field. Is it possible that these are skipped?

**Comment by uerceg** [comment]
Ah, now I see. You are asking about the FB attribution via install referrer content. Unfortunately, we who are first responders in SDK GitHub repos are just familiar with the concept and the fact that it exists, but not sure how much we can help here (dedicated account manager or email to support@adjust.com is probably better way to go). But AFAIK, you should upload FB decryption key to Adjust FB module in dashboard. Did you complete this step?

**Comment by szepag** [comment]
Yes, the decryption key is added. Then I'll try to reach the support, thanks.

**Comment by uerceg** [comment]
Will close this one, but in case you do end up having any other questions, feel free to comment / reopen. Cheers.
