### ISSUE TITLE
requestAppTrackingAuthorization does not work

### ISSUE THREAD

**Issue by PeterKnecht** [adjust/cordova_sdk#192]
In our Angular/Ionic app, we used in v4 of the sdk the method requestTrackingAuthorizationWithCompletionHandler to get the permission for tracking on iOS devices.
After updating to v5 following the migration guide, we adapted the method call to requestAppTrackingAuthorization, however after invoking the method an error is thrown without any error message.

**Comment by uerceg** [comment]
Hey @PeterKnecht,

Thanks for reporting. Do you have any kind of logs printed when trying to invoke this method which might give any kind of hint what might be happening in that moment?

**Comment by PeterKnecht** [comment]
Hey @uerceg,

thank you very much for the quick reply. Unfortunately, there is absolutely no hint of the actual error, from the XCode logs I could only see that an Error is thrown, and the error itself is an empty object, as following

⚡️  [error] - ERROR {}

**Comment by uerceg** [comment]
Thank you for the additional info. Which version of `awesome-cordova-plugins` you use in your app?

**Comment by PeterKnecht** [comment]
6.11.0

**Comment by uerceg** [comment]
Thank you, we'll take a look at this on our end and I'll keep you posted.

**Comment by PeterKnecht** [comment]
Thank you very much!

**Comment by uerceg** [comment]
Hey @PeterKnecht,

Can you please try [v5.0.2](https://github.com/adjust/cordova_sdk/releases/tag/v5.0.2) and let us know if you're still facing this issue with that version?
