### ISSUE TITLE
Is npm install stable?

### ISSUE THREAD

**Issue by piotrowski** [adjust/cordova_sdk#28]
I just saw you added the Cordova-SDK to npm - https://www.npmjs.com/package/com.adjust.sdk - finally, thanks. Is this stable enough to be used in production?

If it is, lots of people would probably benefit a lot by using `cordova plugin add com.adjust.sdk` instead of the current download, unzip, plugin add from local source workflow.

PS: Getting https://www.npmjs.com/package/cordova-plugin-adjust removed from npm would probably be nice, too.

**Comment by uerceg** [comment]
You welcome. It is stable release and it can be used in production as well. 

Even before this release, we had our plugin in cordova plugin repo (not npm) and 'cordova plugin add com.adjust.sdk' works for last few versions. This is first upload to npm repo since all plugins are moving in there.

And as far as 'cordova-plugin-adjust' is concerned, we didn't upload that and that is not official release of ours. Someone made it and uploaded it on his/hers own.

**Comment by piotrowski** [comment]
Oh, didn't know that as the README.md doesn't mention it.

FYI: The npm version is different from the version on the releases page in that the releases-version has empty /ext subfolders where the npm version has them with the intended content.

**Comment by uerceg** [comment]
You are right, we will update README with npm instructions.

And empty ext folder is fine, because in there are git submodules which point to native SDK repositories. We use them just internaly to build native SDK libs, so you don't need them.

**Comment by piotrowski** [comment]
/ext was empty before, by installing using npm it is not and this is causing problems on Windows (paths are too long). If the folder isn't needed for your users, you could probably add it to a .npmignore file: https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package Would appreciate it.

**Comment by piotrowski** [comment]
Shortly forgot that we are on Github... here is PR #29 that adds this.

**Comment by uerceg** [comment]
@piotrowski, thanks for the PR! By excluding this folder from plugin, everything works for Windows users?

**Comment by piotrowski** [comment]
Deleting /ext solved my problems, yes. 
The npm ignore process I can't test :/

**Comment by uerceg** [comment]
Thanks for the update. We'll probably release an update next week with npm ignore file.

**Comment by uerceg** [comment]
@piotrowski We made release with fix you suggested (https://github.com/adjust/cordova_sdk/releases/tag/v4.1.3). Feel free to check current `com.adjust.sdk` in `npm` repository. Unnecessary folders should be ignored now.

Let me know if it worked for you.

**Comment by piotrowski** [comment]
Yes, only /www und /src folders left - as it should be. 

Thanks!
