### ISSUE TITLE
Access callback parameters from SDK?

### ISSUE THREAD

**Issue by piotrowski** [adjust/cordova_sdk#34]
In the callbacks I get information like {adid} or {reftag}. Can I also access these values in the SDK somehow and send them to my backend?

**Comment by uerceg** [comment]
Hi @piotrowski.

We are currently in process of updating our native SDKs with callbacks after event has been tracked. In those callbacks we will try to provide meaningful information to users, among others, `adid` will be one of them.

I will keep you informed on this issue about native SDKs update progress and also Cordova SDK update which will happen afterwards.

Cheers

**Comment by piotrowski** [comment]
Thanks, that sound promising. Will this also include `install``and `session` "events" or only "real" events?

**Comment by piotrowski** [comment]
Ok, if I understood the tickets correctly this should work on all events that trigger a callback.

**Comment by uerceg** [comment]
For the time being, it will only affect events. Not sessions nor installs (install is basically just first session ever). We will think about adding callbacks to session packages as well. Anyway, event callbacks on native SDKs should be released before end of January, so after that we'll start updating our non-native SDKs, including Cordova.

Will keep you posted in here.

**Comment by uerceg** [comment]
Done in https://github.com/adjust/cordova_sdk/releases/tag/v4.10.1.
