### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by Hirbod** [adjust/cordova_sdk#35]
Hi,could you please provide bitcode support? I was forced to remove Adjust due to lack of bitcode support (which is mandatory now)

ld: bitcode bundle could not be generated because 'App/Plugins/com.adjust.sdk/AdjustSdk.framework/AdjustSdk(Adjust.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by uerceg** [comment]
Yes, will be added as soon as possible.

**Comment by uerceg** [comment]
@Hirbod PR for this request is created: https://github.com/adjust/cordova_sdk/pull/36

Once reviewed, will be merged and available in `npm` repository. In the meantime, if you want to run tests with this branch, feel free and let us know if you are still facing error from above.

Cheers

**Comment by uerceg** [comment]
@Hirbod Bitcode support added in newest Cordova version: https://github.com/adjust/cordova_sdk/releases/tag/v4.3.0

Feel free to test it and let us know if it worked. I'll close this issue, feel free to re-open it if you encounter any issues regarding this.

Cheers

**Comment by Hirbod** [comment]
Thanks. I will give it a shot on Monday
