### ISSUE TITLE
update native sdk dependencies to latest

### ISSUE THREAD

**Issue by samzilverberg** [adjust/cordova_sdk#43]
ios/android sdks were not updated since Feb 2016.

please update to latest available:
android 4.7.0
ios 4.9.0

ios is especially important because of fixes related to iOS 10!

**Comment by uerceg** [comment]
Hi,

Sure, we are planning updates of all non native SDKs to be compatible with this iOS release. 

Will keep you posted. 

Cheers

**Comment by krik** [comment]
@uerceg any news on the issue? In your activity stream I've seen you committing updates to other platforms such as Unity, Xamarin, etc

**Comment by uerceg** [comment]
Hi @krik 

Yep, we're updating all non natives in parallel and Cordova release is aimed for the next week.

Cheers

**Comment by csjits** [comment]
Hi @uerceg 

Any updates on this? Will there be an update for Cordova available this week?

**Comment by uerceg** [comment]
Yes, we're finishing it and still aiming to get it done this week. We are in final stages of 4.10.0 implementation. Our tech team is on the retreat for next 7 days, so things might get a bit delayed, but will keep you posted.

**Comment by csjits** [comment]
@uerceg Do you have any new estimates?

**Comment by uerceg** [comment]
Hi @csjits,

And sorry for a bit delayed answer. Update is coming early next week. Most probably Monday. 

Cheers

**Comment by uerceg** [comment]
https://github.com/adjust/cordova_sdk/releases/tag/v4.10.0

**Comment by samzilverberg** [comment]
thanks! 👍
