### ISSUE TITLE
Android - adjustConfig.setLogLevel generate an exception if AdjustConfig.EnvironmentProduction is set

### ISSUE THREAD

**Issue by logicweb** [adjust/cordova_sdk#53]
Hi, 
I have found an issue on the Android part if you call the setLogLevel when AdjustConfig.EnvironmentProduction is set.
Here the error from the logcat:

```
03-27 12:16:15.240: E/PluginManager(26062): Uncaught exception from plugin
03-27 12:16:15.240: E/PluginManager(26062): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
03-27 12:16:15.240: E/PluginManager(26062): at com.adjust.sdk.AdjustCordova.executeCreate(AdjustCordova.java:293)
03-27 12:16:15.240: E/PluginManager(26062): at com.adjust.sdk.AdjustCordova.execute(AdjustCordova.java:121)
```

Don't calling the setLogLevel method resolve the issue.
On iOS everything seems fine.
Thanks

**Comment by uerceg** [comment]
Hi @logicweb 

Thanks for reporting, we will take a look at this and get back to you once we try to reproduce this.

For the record, which log level were you trying to set?

Cheers

**Comment by logicweb** [comment]
Ok, I have verified and found an error on the Adjust.d.ts that we were using (our app is written in TypeScript).

You can close this issue.
Thanks

**Comment by uerceg** [comment]
Thanks for the update. 👍
