### ISSUE TITLE
Adjust.h missing on iOS

### ISSUE THREAD

**Issue by ventr1x** [adjust/cordova_sdk#62]
Hey,

what is the official state of the cordova plugin?
Currently I am unable to build any app with adjust for iOS (tested 4.11.&4.12.).
I didn't have that problem 2 months ago and it might be related to new phonegap versions (using cli-7.1.0)

Using build.phonegap:

`CompileC /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/Objects-normal/armv7/AdjustCordovaDelegate.o appname/Plugins/com.adjust.sdk/AdjustCordovaDelegate.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode92.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -DCOCOAPODS=1 -DCOCOAPODS=1 -isysroot /Applications/Xcode92.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=9.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -iquote /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/appname-generated-files.hmap -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/appname-own-target-headers.hmap -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/appname-all-target-headers.hmap -iquote /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/appname-project-headers.hmap -I/project/build/include -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/InstallationBuildProductsLocation/Applications/usr/local/lib/include -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/UninstalledProducts/include -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/include -I/project/build -I/project/Pods/Headers/Public -I/project/Pods/Headers/Public/GGLInstanceID -I/project/Pods/Headers/Public/GoogleCloudMessaging -I/project/Pods/Headers/Public/GoogleIPhoneUtilities -I/project/Pods/Headers/Public/GoogleInterchangeUtilities -I/project/Pods/Headers/Public/GoogleSymbolUtilities -I/project/Pods/Headers/Public/GoogleUtilities -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/DerivedSources/armv7 -I/Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/DerivedSources -F/project/build -F/project/Pods/GoogleIPhoneUtilities/Frameworks -F/project/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/project/Pods/GoogleSymbolUtilities/Frameworks/frameworks -F/project/Pods/GoogleUtilities/Frameworks/frameworks -Fappname/Plugins/com.adjust.sdk -Fappname/Plugins/cordova-plugin-facebook4 -isystem /project/Pods/Headers/Public -isystem /project/Pods/Headers/Public/GGLInstanceID -isystem /project/Pods/Headers/Public/GoogleCloudMessaging -isystem /project/Pods/Headers/Public/GoogleIPhoneUtilities -isystem /project/Pods/Headers/Public/GoogleInterchangeUtilities -isystem /project/Pods/Headers/Public/GoogleSymbolUtilities -isystem /project/Pods/Headers/Public/GoogleUtilities -isystem /project/Pods/Headers/Public -isystem /project/Pods/Headers/Public/GGLInstanceID -isystem /project/Pods/Headers/Public/GoogleCloudMessaging -isystem /project/Pods/Headers/Public/GoogleIPhoneUtilities -isystem /project/Pods/Headers/Public/GoogleInterchangeUtilities -isystem /project/Pods/Headers/Public/GoogleSymbolUtilities -isystem /project/Pods/Headers/Public/GoogleUtilities -include /private/project/build/sharedpch/appname-Prefix-bverarvgruvmkegbldrowutncnfb/appname-Prefix.pch -MMD -MT dependencies -MF /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/Objects-normal/armv7/AdjustCordovaDelegate.d --serialize-diagnostics /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/Objects-normal/armv7/AdjustCordovaDelegate.dia -c /project/appname/Plugins/com.adjust.sdk/AdjustCordovaDelegate.m -o /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/Objects-normal/armv7/AdjustCordovaDelegate.o
In file included from /project/appname/Plugins/com.adjust.sdk/AdjustCordovaDelegate.m:11:
appname/Plugins/com.adjust.sdk/AdjustCordovaDelegate.h:10:9: fatal error: 'AdjustSdk/Adjust.h' file not found
#import <AdjustSdk/Adjust.h>`

`The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/appname-araeacpzaxeyvoctlcqhzskwppzu/Build/Intermediates.noindex/ArchiveIntermediates/appname/IntermediateBuildFilesPath/appname.build/Release-iphoneos/appname.build/Objects-normal/armv7/AdjustCordovaDelegate.o appname/Plugins/com.adjust.sdk/AdjustCordovaDelegate.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,appname.xcworkspace,-scheme,appname,-configuration,Release,-destination,generic/platform=iOS,-archivePath,appname.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch`

**Comment by uerceg** [comment]
Hi @ventr1x 

Can you tell me which Xcode version are you using on you machine?

**Comment by ventr1x** [comment]
I mostly use Adobe's phonegap build https://build.phonegap.com
Their logs suggest they're using xcode 9.2 and iPhoneOS11.2.sdk

**Comment by uerceg** [comment]
@ventr1x Do you have possibility (for testing sake) to add our plugin from specific branch on our public repository? Something like described in this chapter: https://cordova.apache.org/docs/en/3.3.0/guide/cli/index.html#advanced-plugin-options

```
cordova plugin add https://github.com/apache/cordova-plugin-console.git#r0.2.0
```

If you have this possibility, we would prepare some modified version of plugin for you to test it if it works and if yes, make it official one.

**Comment by ventr1x** [comment]
Yes, that should be no problem.
I'd be happy to help.

**Comment by uerceg** [comment]
Lovely. Will get things ready soon and ping you in here once done. Thanks!

**Comment by uerceg** [comment]
@ventr1x Can you try adding our SDK from `v4123` branch of our repository and let us know if you are still facing this issue?

Thanks in advance!

**Comment by ventr1x** [comment]
I don't have the time atm to test the sdk itself, but building and running the app works fine with this version.

**Comment by uerceg** [comment]
Awesome, that's all we needed. Thanks! 👍

**Comment by uerceg** [comment]
@ventr1x 

For the record, we have updated our plugin to `v4.12.3`. Feel free to to use that version from `npm` repo (or Github `master` branch, not sure how you use it), no need to use this test version from `v4123`. Let us know if it worked and if the issue is solved.

Looking forward to hear from you and thanks for bringing this up.

Cheers.

**Comment by Obaied** [comment]
Hey @ventr1x.
Is the issue still open?
