### ISSUE TITLE
Bug: no "setDeviceToken" function

### ISSUE THREAD

**Issue by Hirbod** [adjust/cordova_sdk#71]
The README states that there is a "setDeviceToken" function, but it's undefined.
Not sure if this is a documentation issue only, but I just found a "setPushToken()" function

**Comment by uerceg** [comment]
@Hirbod Thanks for reporting, nice catch. It's docs only. Will ping you in here once fixed.

**Comment by uerceg** [comment]
It's fixed now. Thanks one more time for spotting it. Cheers! 🍺

**Comment by Hirbod** [comment]
you're welcome!
