### ISSUE TITLE
Capacitor Support

### ISSUE THREAD

**Issue by sandstrom** [adjust/cordova_sdk#74]
Curious to hear if you have verified if your plugin works with Capacitor (an open-source project based on, and similar to, Cordova)?

More details:
https://github.com/ionic-team/capacitor
https://capacitor.ionicframework.com/docs/basics/cordova

**Comment by uerceg** [comment]
Hi @sandstrom 

No, we didn't do any tests when it comes to checking functionality of our SDK with apps made with this framework. We're usually not investigating things like this on our own, we're mostly driven by requests from our product team to check things like this in case they estimate that it makes sense for us to check it out and support.

**Comment by sandstrom** [comment]
Got it, thanks for the update! 

Capacitor is still fairly early too, so no need to dig into it now.

Much thanks @uerceg!
