### ISSUE TITLE
Cordova 8 support with cordova-android < 7.0.0

### ISSUE THREAD

**Issue by Morathil** [adjust/cordova_sdk#77]
Hey, we are using cordova 8 with cordova-android 6.4.0.

We can not add the master branch because it does not support cordova 8 (package.json needs to be updated) and we can not use the cordova-8 branch either because we are using cordova-android 6.4.0 (results in `java.lang.ClassNotFoundException: com.adjust.sdk.AdjustCordova`).

Can you please support cordova 8 with the master branch?

**Comment by uerceg** [comment]
Hi @Morathil 

So you are facing problem with adding our official SDK version to your app with usage of `Cordova 8` and `cordova-android@6.4.0`? We were testing this combination when Cordova 8 was released and that used to work without any issues, the only issue was if `cordova-android@7.0.0` was used with Cordova 8.

What kind of error are you seeing when adding our plugin via NPM to your app with usage of `cordova 8.0.0` and `cordova-android@6.4.0`? Also, if you can share with us what `package.json` change would be needed?

Looking forward to hear from you.

Cheers

**Comment by Morathil** [comment]
Exactly.
When i try to add the plugin with `cordova plugin add com.adjust.sdk` just nothing happens.
But i can add the cordova-8 branch with `cordova plugin add https://github.com/adjust/cordova_sdk.git#cordova-8`.

What worked for me is forking the official plugin and running `plugman createpackagejson .` which leads into these changes https://github.com/platogo/cordova_adjust/commit/f94345d58dde8f4796329f343e4fa884d79fa1c6

I also had a look at your cordova-8 branch and there you only added a `repository` section to the `package.json` https://github.com/adjust/cordova_sdk/commit/114fb7671b405b0b19c251ca81c10c7a0c20ea0a what also seems to work for me. So I guess just the `repository` section is missing.

Cheers

**Comment by uerceg** [comment]
Huh, really interesting. Thanks for reporting this and thanks for the fork diffs. We'll test adding our current SDK v4.14.0 to app made with `cordova 8.0.0` and `cordova-android@6.4.0` and see if we can reproduce this issue you're facing. Will keep you posted.

**Comment by Morathil** [comment]
Hey @uerceg, is there an update to this issue?

**Comment by Morathil** [comment]
@uerceg I tried it again with a new cordova 8 app an there it worked. :( I have no idea why it didn't work for our app... 🤔 I copied over the config.xml entry and the package.json entry for adjust and now it also works for our app...

Sorry for bothering...

**Comment by uerceg** [comment]
No problemo, glad it worked for you at the end. Feel free to ping us in here when ever you face some issue. Cheers. 🍺
