### ISSUE TITLE
package org.apache.http.client does not exist

### ISSUE THREAD

**Issue by thesayyn** [adjust/cordova_sdk#78]
I'm getting an error like so when i run 

Envrionment

cordova: 8.0.0
cordova-android: 6.4.0

Installed Plugins

com.adjust.sdk 3.4.1 "Adjust"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-facebook4 1.10.1 "Facebook Connect"
cordova-plugin-firebase-analytics 1.0.0 "FirebaseAnalyticsPlugin"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-inapppurchase 1.1.0 "In App Purchase"
cordova-plugin-intercom 3.2.2 "Intercom"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-screen-orientation 2.0.2 "Screen Orientation"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-streaming-media 2.1.2 "StreamingMedia"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.1 "SocialSharing"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
cordova-support-android-plugin 1.0.1 "cordova-support-android-plugin"
cordova-support-google-services 1.2.1 "cordova-support-google-services"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"

$ cordova run android

`
ANDROID_HOME=/usr/local/Caskroom/android-sdk/3859397
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home
Subproject Path: CordovaLib
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_5urs8dv1xmzr9q32cuoq7wev6.run(/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/build.gradle:144)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
:preBuild UP-TO-DATE
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:checkDebugManifest UP-TO-DATE
:CordovaLib:processDebugManifest UP-TO-DATE
:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl UP-TO-DATE
:compileDebugAidl UP-TO-DATE
:CordovaLib:packageDebugRenderscript NO-SOURCE
:compileDebugRenderscript UP-TO-DATE
:checkDebugManifest UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:prepareLintJar UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:processDebugGoogleServices
Parsing json file: /Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/google-services.json
:CordovaLib:compileDebugRenderscript UP-TO-DATE
:CordovaLib:generateDebugResValues UP-TO-DATE
:CordovaLib:generateDebugResources UP-TO-DATE
:CordovaLib:packageDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:createDebugCompatibleScreenManifests UP-TO-DATE
:processDebugManifest UP-TO-DATE
:splitsDiscoveryTaskDebug UP-TO-DATE
:CordovaLib:platformAttrExtractor UP-TO-DATE
:CordovaLib:processDebugResources UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:CordovaLib:generateDebugBuildConfig UP-TO-DATE
:CordovaLib:prepareLintJar UP-TO-DATE
:CordovaLib:generateDebugSources UP-TO-DATE
:CordovaLib:javaPreCompileDebug UP-TO-DATE
:CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
:CordovaLib:processDebugJavaRes NO-SOURCE
:CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
:javaPreCompileDebug UP-TO-DATE
:compileDebugJavaWithJavac/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:3: error: package org.apache.http.client does not exist
import org.apache.http.client.HttpClient;
                             ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:4: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.DefaultHttpClient;
                                  ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:13: error: cannot find symbol
    private static HttpClient httpClient = null;
                   ^
  symbol:   class HttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:41: error: cannot find symbol
    public static HttpClient getHttpClient(HttpParams params) {
                  ^
  symbol:   class HttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:81: error: cannot find symbol
    public static void setHttpClient(HttpClient httpClient) {
                                     ^
  symbol:   class HttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:22: error: cannot find symbol
import org.apache.http.HttpResponse;
                      ^
  symbol:   class HttpResponse
  location: package org.apache.http
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:23: error: cannot find symbol
import org.apache.http.HttpStatus;
                      ^
  symbol:   class HttpStatus
  location: package org.apache.http
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:24: error: cannot find symbol
import org.apache.http.NameValuePair;
                      ^
  symbol:   class NameValuePair
  location: package org.apache.http
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:25: error: package org.apache.http.client does not exist
import org.apache.http.client.ClientProtocolException;
                             ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:26: error: package org.apache.http.client does not exist
import org.apache.http.client.HttpClient;
                             ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:27: error: package org.apache.http.client.entity does not exist
import org.apache.http.client.entity.UrlEncodedFormEntity;
                                    ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:28: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpPost;
                                     ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:29: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpUriRequest;
                                     ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:30: error: package org.apache.http.client.utils does not exist
import org.apache.http.client.utils.URLEncodedUtils;
                                   ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:31: error: package org.apache.http.message does not exist
import org.apache.http.message.BasicNameValuePair;
                              ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:32: error: cannot find symbol
import org.apache.http.params.BasicHttpParams;
                             ^
  symbol:   class BasicHttpParams
  location: package org.apache.http.params
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:48: error: cannot find symbol
    private HttpClient      httpClient;
            ^
  symbol:   class HttpClient
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:130: error: cannot find symbol
    private void requestFinished(HttpResponse response, ActivityPackage activityPackage) {
                                 ^
  symbol:   class HttpResponse
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:149: error: cannot find symbol
    private String parseResponse(HttpResponse response) {
                                 ^
  symbol:   class HttpResponse
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:193: error: cannot find symbol
    private HttpUriRequest getRequest(ActivityPackage activityPackage) throws UnsupportedEncodingException {
            ^
  symbol:   class HttpUriRequest
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:43: error: cannot find symbol
            return new DefaultHttpClient(params);
                       ^
  symbol:   class DefaultHttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:106: error: cannot find symbol
        HttpParams httpParams = new BasicHttpParams();
                                    ^
  symbol:   class BasicHttpParams
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:114: error: cannot find symbol
            HttpUriRequest request = getRequest(activityPackage);
            ^
  symbol:   class HttpUriRequest
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:115: error: cannot find symbol
            HttpResponse response = httpClient.execute(request);
            ^
  symbol:   class HttpResponse
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:119: error: cannot find symbol
        } catch (ClientProtocolException e) {
                 ^
  symbol:   class ClientProtocolException
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:136: error: cannot find symbol
        if (HttpStatus.SC_OK == statusCode) {
            ^
  symbol:   variable HttpStatus
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:195: error: cannot find symbol
        HttpPost request = new HttpPost(url);
        ^
  symbol:   class HttpPost
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:195: error: cannot find symbol
        HttpPost request = new HttpPost(url);
                               ^
  symbol:   class HttpPost
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:202: error: cannot find symbol
        List<NameValuePair> pairs = new ArrayList<NameValuePair>();
             ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:202: error: cannot find symbol
        List<NameValuePair> pairs = new ArrayList<NameValuePair>();
                                                  ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:204: error: cannot find symbol
            NameValuePair pair = new BasicNameValuePair(entity.getKey(), entity.getValue());
            ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:204: error: cannot find symbol
            NameValuePair pair = new BasicNameValuePair(entity.getKey(), entity.getValue());
                                     ^
  symbol:   class BasicNameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:210: error: cannot find symbol
        NameValuePair sentAtPair = new BasicNameValuePair("sent_at", dateString);
        ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:210: error: cannot find symbol
        NameValuePair sentAtPair = new BasicNameValuePair("sent_at", dateString);
                                       ^
  symbol:   class BasicNameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:213: error: cannot find symbol
        UrlEncodedFormEntity entity = new UrlEncodedFormEntity(pairs);
        ^
  symbol:   class UrlEncodedFormEntity
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:213: error: cannot find symbol
        UrlEncodedFormEntity entity = new UrlEncodedFormEntity(pairs);
                                          ^
  symbol:   class UrlEncodedFormEntity
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:214: error: cannot find symbol
        entity.setContentType(URLEncodedUtils.CONTENT_TYPE);
                              ^
  symbol:   variable URLEncodedUtils
  location: class RequestHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
37 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
28 actionable tasks: 2 executed, 26 up-to-date
(node:10408) UnhandledPromiseRejectionWarning: Error: /Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:3: error: package org.apache.http.client does not exist
import org.apache.http.client.HttpClient;
                             ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:4: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.DefaultHttpClient;
                                  ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:13: error: cannot find symbol
    private static HttpClient httpClient = null;
                   ^
  symbol:   class HttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:41: error: cannot find symbol
    public static HttpClient getHttpClient(HttpParams params) {
                  ^
  symbol:   class HttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:81: error: cannot find symbol
    public static void setHttpClient(HttpClient httpClient) {
                                     ^
  symbol:   class HttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:22: error: cannot find symbol
import org.apache.http.HttpResponse;
                      ^
  symbol:   class HttpResponse
  location: package org.apache.http
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:23: error: cannot find symbol
import org.apache.http.HttpStatus;
                      ^
  symbol:   class HttpStatus
  location: package org.apache.http
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:24: error: cannot find symbol
import org.apache.http.NameValuePair;
                      ^
  symbol:   class NameValuePair
  location: package org.apache.http
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:25: error: package org.apache.http.client does not exist
import org.apache.http.client.ClientProtocolException;
                             ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:26: error: package org.apache.http.client does not exist
import org.apache.http.client.HttpClient;
                             ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:27: error: package org.apache.http.client.entity does not exist
import org.apache.http.client.entity.UrlEncodedFormEntity;
                                    ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:28: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpPost;
                                     ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:29: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpUriRequest;
                                     ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:30: error: package org.apache.http.client.utils does not exist
import org.apache.http.client.utils.URLEncodedUtils;
                                   ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:31: error: package org.apache.http.message does not exist
import org.apache.http.message.BasicNameValuePair;
                              ^
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:32: error: cannot find symbol
import org.apache.http.params.BasicHttpParams;
                             ^
  symbol:   class BasicHttpParams
  location: package org.apache.http.params
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:48: error: cannot find symbol
    private HttpClient      httpClient;
            ^
  symbol:   class HttpClient
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:130: error: cannot find symbol
    private void requestFinished(HttpResponse response, ActivityPackage activityPackage) {
                                 ^
  symbol:   class HttpResponse
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:149: error: cannot find symbol
    private String parseResponse(HttpResponse response) {
                                 ^
  symbol:   class HttpResponse
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:193: error: cannot find symbol
    private HttpUriRequest getRequest(ActivityPackage activityPackage) throws UnsupportedEncodingException {
            ^
  symbol:   class HttpUriRequest
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/AdjustFactory.java:43: error: cannot find symbol
            return new DefaultHttpClient(params);
                       ^
  symbol:   class DefaultHttpClient
  location: class AdjustFactory
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:106: error: cannot find symbol
        HttpParams httpParams = new BasicHttpParams();
                                    ^
  symbol:   class BasicHttpParams
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:114: error: cannot find symbol
            HttpUriRequest request = getRequest(activityPackage);
            ^
  symbol:   class HttpUriRequest
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:115: error: cannot find symbol
            HttpResponse response = httpClient.execute(request);
            ^
  symbol:   class HttpResponse
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:119: error: cannot find symbol
        } catch (ClientProtocolException e) {
                 ^
  symbol:   class ClientProtocolException
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:136: error: cannot find symbol
        if (HttpStatus.SC_OK == statusCode) {
            ^
  symbol:   variable HttpStatus
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:195: error: cannot find symbol
        HttpPost request = new HttpPost(url);
        ^
  symbol:   class HttpPost
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:195: error: cannot find symbol
        HttpPost request = new HttpPost(url);
                               ^
  symbol:   class HttpPost
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:202: error: cannot find symbol
        List<NameValuePair> pairs = new ArrayList<NameValuePair>();
             ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:202: error: cannot find symbol
        List<NameValuePair> pairs = new ArrayList<NameValuePair>();
                                                  ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:204: error: cannot find symbol
            NameValuePair pair = new BasicNameValuePair(entity.getKey(), entity.getValue());
            ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:204: error: cannot find symbol
            NameValuePair pair = new BasicNameValuePair(entity.getKey(), entity.getValue());
                                     ^
  symbol:   class BasicNameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:210: error: cannot find symbol
        NameValuePair sentAtPair = new BasicNameValuePair("sent_at", dateString);
        ^
  symbol:   class NameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:210: error: cannot find symbol
        NameValuePair sentAtPair = new BasicNameValuePair("sent_at", dateString);
                                       ^
  symbol:   class BasicNameValuePair
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:213: error: cannot find symbol
        UrlEncodedFormEntity entity = new UrlEncodedFormEntity(pairs);
        ^
  symbol:   class UrlEncodedFormEntity
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:213: error: cannot find symbol
        UrlEncodedFormEntity entity = new UrlEncodedFormEntity(pairs);
                                          ^
  symbol:   class UrlEncodedFormEntity
  location: class RequestHandler
/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/src/com/adjust/sdk/RequestHandler.java:214: error: cannot find symbol
        entity.setContentType(URLEncodedUtils.CONTENT_TYPE);
                              ^
  symbol:   variable URLEncodedUtils
  location: class RequestHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
37 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
    at ChildProcess.whenDone (/Users/thesayyn/Documents/ionic projects/niix-app/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:10408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by uerceg** [comment]
Hi @thesayyn 

Is there any reason for using such an old version of Adjust SDK? Are you seeing this error if you give our latest SDK version (v4.14.0) a try?

**Comment by thesayyn** [comment]
problem solved thanks
