### ISSUE TITLE
Build error after installing plugin

### ISSUE THREAD

**Issue by brad426** [adjust/cordova_sdk#79]
MacOS
Cordova 8.1.1 (cordova-lib@8.1.0)
Cordova Android 7.1.1

After installing the plugin using `cordova plugin add https://github.com/adjust/cordova_sdk.git#cordova-8`
And trying to build my app for Android, i get the following error message:
```
> Task :app:compileDebugJavaWithJavac FAILED
.../cordova/platforms/android/app/src/main/java/cordova/plugin/RequestLocationAccuracy.java:55: error: cannot access zzbfm
        ResultCallback<LocationSettingsResult> {
                      ^
  class file for com.google.android.gms.internal.zzbfm not found

```

So the error actually comes form the `RequestLocationAccuracy` plugin, but after removing the adjust plugin, the app will build fine

**Comment by uerceg** [comment]
Hi @brad426 

Sorry for delay in reply.

Hm. Weird. I am not sure how is our plugin causing this issue. This issue seems maybe related to yours (https://stackoverflow.com/questions/38073706/class-file-for-com-google-android-gms-internal-zzaja-not-found), are you maybe using something from things mentioned in the thread?

**Comment by brad426** [comment]
hi @uerceg 

No, we're not using anything mentioned in that SO post.
Our plugins usage is as follows:
``` javascript
    "card.io.cordova.mobilesdk": "git+https://github.com/card-io/card.io-Cordova-Plugin.git",
    "cordova-android": "^7.1.1",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-facebook4": "^1.9.1",
    "cordova-plugin-geolocation": "^2.4.3",
    "cordova-plugin-inappbrowser": "^1.7.2",
    "cordova-plugin-request-location-accuracy": "^2.2.2",
    "cordova-plugin-speechrecognition": "^1.2.0",
    "cordova-plugin-splashscreen": "^4.1.0",
    "cordova-plugin-statusbar": "^2.3.0",
    "cordova-plugin-whitelist": "^1.3.2"
```

**Comment by uerceg** [comment]
Hi @brad426 

Is this still an issue for you and if yes, does it still occur with our latest SDK version?

Cheers

**Comment by uerceg** [comment]
In case the issue still persists with latest SDK version, feel free to reopen the issue. Cheers!
