### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by samirpramanik** [adjust/cordova_sdk#92]
We are facing a build issue, which was earlier working fine. We are using the version 4.14.0.
The error is as below :
No resource identifier found for attribute \'appComponentFactory\' in package \'android\'

**Comment by uerceg** [comment]
Hi @samirpramanik

Can you maybe provide more detailed build log output? I can't really see how can this be tied to our Cordova SDK at this moment.

**Comment by samirpramanik** [comment]
Sure. PFA the complete logs.
[adjustBuildFail.txt](https://github.com/adjust/cordova_sdk/files/3342593/adjustBuildFail.txt)

**Comment by uerceg** [comment]
Hm. I am not sure how does this relate to Adjust SDK. Can you explain to me what makes you think that our SDK is source of the issue?

From what I see:

```
myWorkspace\cordovatemp\platforms\android\build\intermediates\manife
sts\full\debug\AndroidManifest.xml:27: AAPT: No resource identifier found for at
tribute 'appComponentFactory' in package 'android'
```

Seems like `aapt` is failing when processing your manifest file. What is in line 27 of it during this build process?

**Comment by samirpramanik** [comment]
We are seeing this issue only after we add the adjust sdk to our project. Please find attached the manifest file as well. In line 27, it has the following : 
<application
        android:appComponentFactory="androidx.core.app.CoreComponentFactory"

This earlier used to refer to v4 support factory. Now it refers to androidx.core.app.CoreComponentFactory. But there is no plugin change or dependencies change from our end.
[AndroidManifest .txt](https://github.com/adjust/cordova_sdk/files/3342643/AndroidManifest.txt)

**Comment by uerceg** [comment]
Thanks for info. Still not sure how this relates to our SDK. Will try to see if we can reproduce this behavior. 

Which Cordova version and `cordova-android` platform version are you using?

**Comment by samirpramanik** [comment]
We are using cordova 8.0.0. Earlier we were on 6.5.0, but we upgraded and the issue still remains.
Cordova android patform version is 6.1.2

**Comment by uerceg** [comment]
Thanks. We will try to see if we can reproduce this issue and keep you posted in here.

**Comment by samirpramanik** [comment]
Were you able to reproduce this? For us, it started suddenly. The same sdk was working perfectly before and we did not change even the versions.

**Comment by uerceg** [comment]
I still didn't manage to reproduce this issue even though I am using same environment you described. Does the same issue happen if you update `cordova-android` platform to latest version?

**Comment by uerceg** [comment]
@samirpramanik Any update on this one?

**Comment by philippmayrth** [comment]
> For us, it started suddenly.

We are facing the same bug it also happened suddenly for us. When we remove Adjust it's building perfectly.

@samirpramanik How did you fix it?

**Comment by samirpramanik** [comment]
Enabling jetifier and using androidx helped us resolve this issue at our end.

**Comment by uerceg** [comment]
@philippmayrth Did this solution work for you?
