### ISSUE TITLE
Process for checking the installs for marketing campaigns

### ISSUE THREAD

**Issue by phanikumar560** [adjust/cordova_sdk#96]
Hi Team,
We are able to integrate the SDK in our code and able to check the installs for organic in sandbox mode. 

We want to have two marketing campaigns.
One is SMS and other EMAIL. So we have created tracker urls for both SMS and Email.

We appreciate your quick response on the below queries.
1)Could you please let us know the procedure to check no of installs using the tracker urls.
2)What is the code need to be added for checking this.
3)Is there any process for checking the no of installs for marketing campaigns in sandbox mode.

Thanks
Phani

**Comment by uerceg** [comment]
Hi @phanikumar560 

You can test if your app install is getting attributed to click on given tracker URL by performing following:

1. Make sure that your tracker and/or tracker URL is configured properly. Meaning that if you're using tracker URL without your test device's advertising ID appended to it, make sure that fingerprinting for clicks is enabled for your test tracker (it's off by default). If you put device's advertising ID to tracker URL, then fingerprinting setting doesn't matter.
2. Uninstall app from your test device.
3. Forget your test device from Testing Console in Adjust dashboard in case you have already been running some tests with it.
4. Click on tracker URL.
5. Install an app on test device and start Adjust SDK.

This should be it. SDK will track install session and if everything configured properly like described above, that install should get attributed to the click on tracker UR you did in step 4. You can also easily check this right away from SDK logs when attribution information arrives to SDK (visible in sandbox mode with verbose log level configured) and also later in dashboard numbers for given tracker as well.

To give explicit answer to your questions:

1. This is what is described above.
2. No additional code needed, if you see installs being tracked in your tests, that's all it takes.
3. If you perform test described above with SDK environment set to sandbox, then that attributed install will be the one made in sandbox mode and visible in Adjust dashboard under sandbox mode traffic.

In case you have any further questions, feel free to ping.

Cheers

**Comment by phanikumar560** [comment]
Hi Team,

Thanks a lot for the quick response.

Could you please let us know whether is there any process to check the no of installs by clicking the tracker urls without pointing to playstore/App Store ?

For testing purpose we have different bundle identifiers for different environments[development & testing] for which we don't have apps in the appstore/playstore.

So Is there any process to check that pointing to our internal playstores?


Thanks
Phani

**Comment by uerceg** [comment]
@phanikumar560 

Click on tracker URL will always redirect you to the store where your app exists, that's just how tracker URLs work. But if you wanna perform test with the build of your app which is not in the store, feel free to simply ignore redirection to the store upon clicking the URL and just install desired app build to test device after click/redirection logic took place.

Having different bundle IDs / package names is perfectly fine and won't affect tracking as long as you use proper app token inside of those builds. Also like said above, existence of app with that bundle ID / package name in the store is not important.

Cheers

**Comment by uerceg** [comment]
@phanikumar560 

Any update on this one?

**Comment by ugi** [comment]
Feel free to reopen/comment if needed. Cheers.
