### ISSUE TITLE
OAID plugin

### ISSUE THREAD

**Issue by Morathil** [adjust/cordova_sdk#97]
We are currently in contact with your support as we have an issue that `gps_adid` is sometimes empty in callbacks our server receives.

Your support suggested to implement OAID (https://github.com/adjust/android_sdk/blob/master/doc/english/plugins/oaid.md) to support some Chinese-Manufacturers (Huawei).

Is this something that should be added directly to the Cordova plugin or how should we best implement it?

**Comment by uerceg** [comment]
Hi @Morathil,

We have added OAID support just for native Android SDK and also we have built the plugin for Unity SDK. At this moment, we don't have dedicated plugin built for Cordova.

Best shot you have if you wanna use it from your Cordova app at the moment would probably be to go to your Android app's native Android Studio project and maybe add our OAID plugin from Maven in there as if you were adding it to the native Android app.

**Comment by Morathil** [comment]
Hi @uerceg 

Thanks for your response. I think I know how to add the OAID plugin but i have troubles understanding the whole `Add the MSA SDK to your app` section as the link redirects to a Chinese page. Is there an english version of the instructions and is it possible to download the sdk without registering?

Also not really clear is the `Use the plugin` section. Do we have to adjust code of the cordova adjust plugin?

Can you help us with this?

**Comment by shashanksu** [comment]
Hi @Morathil 

I am afraid there is no English version of the page and you will have to register to download the sdk.  Now once you download the `miit_mdid_1.0.10.aar` (or higher version), just to ease your integration steps, please follow these instructions -
1. Copy the _aar_ into `libs` folder 
2. Add the _aar_ dependency in the project `build.gradle`
3. Update to proguard rules, add `-keep class com.bun.miitmdid.core.** {*;} `
4. Add the _adjust oaid plugin_ dependency in the project `build.gradle`
5. Enable the oaid plugin to read the oaid, call - `AdjustOaid.readOaid(applicationContext);` before calling `Adjust.onCreate(config);`

This should be good to integrate oaid plugin.  Hope this helps.

**Comment by Morathil** [comment]
Thanks for your reply!
I'm closing this issue as the OAID plugin isn't part of your Cordova plugin anyways at the moment.
