### ISSUE TITLE
appDidLaunch issue ionic cordova ios app only

### ISSUE THREAD

**Issue by NagendraMNK** [adjust/cordova_sdk#98]
2020-02-28 23:23:28.142061+0530 App_Name[55521:2623924] [CDVTimer][adjust] 0.329018ms
2020-02-28 23:23:48.679820+0530 App_Name [55521:2623924] 	[Adjust]e: Please initialize Adjust by calling 'appDidLaunch' before
2020-02-28 23:23:48.679940+0530 App_Name [55521:2623924] THREAD WARNING: ['Adjust'] took '10.363037' ms. Plugin should use a background thread.

I am using this in ionic4 and after platform ready, 10days back it worked and now giving above issue, could you please help here

**Comment by NagendraMNK** [comment]
i am unable to find appDidLaunch in adjust.ts

Please suggest me here

this.adjust.appDidLaunch(adjustConfig)

**Comment by NagendraMNK** [comment]
Can you suggest me Adjust cordova and ionic version for iOS

**Comment by uerceg** [comment]
Hi @NagendraMNK.

These logs are originating from native iOS SDK. Meaning of the log line is that some action was attempted to be performed on Adjust SDK before you have invoked [`create`](https://github.com/adjust/cordova_sdk/blob/master/ionic-native/index.ts#L298) method on Adjust instance. `appDidLaunch:` method is just what is being called under the hood in native iOS SDK of ours.

How are you setting up SDK inside of your app?  Did you check our [example implementation](https://github.com/adjust/cordova_sdk/blob/master/example-ionic/src/app/app.component.ts) inside of the Ionic app?

Cheers

**Comment by NagendraMNK** [comment]
I am not creating any event before configuration set,  creating an event in AddToCart and Purchase not in app launch

**Comment by uerceg** [comment]
Okay. Can you launch your app with Adjust SDK set to sandbox environment and log level set to verbose and upon launch, pick up all the logs which Adjust SDK outputs (you can find them with **[Adjust]** tag and feel free to remove any sensitive information from them if any present) and send them over?

**Comment by NagendraMNK** [comment]
[CDVTimer][adjust] 0.084996ms
[Adjust]e: Please initialize Adjust by calling 'appDidLaunch' before

I am getting those two logs, first one is coming when app is launching and second one when i am calling trackEvent

As my understanding, First log is blocking my all trackevents and this is happening only in iOS

**Comment by ugi** [comment]
Hi @NagendraMNK 

Sorry for delay in response. Are you still encountering this with latest SDK version?

**Comment by uerceg** [comment]
Feel free to comment/reopen in case issue still persists with latest SDK version. Cheers.
